name: test

on:
  schedule:
    - cron: '40 18 * * *'
  workflow_dispatch:

jobs:
 build:

    runs-on: ubuntu-latest
    timeout-minutes: 280
    
    permissions:
      contents: read
      actions: write
    steps:
      - name: Debug Time
        run: date
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: app
        run: |
          chmod +x entrypoint.sh

      - name: app run
        run: |
          bash entrypoint.sh
